FROM golang:1.20

# get go-ethereum
RUN git clone https://github.com/ethereum/go-ethereum.git

# build abigen from go-ethereum
RUN cd go-ethereum && env GOBIN= go install ./cmd/abigen

# copy contract bytecode & ABI generate by forge to container
ADD ./out /root/buidl-wallet-contracts

# copy detination folder to container for volume mounting
ADD ./abigen /root/buidl-wallet-contracts
