[profile.default]
fs_permissions = [{ access = "read-write", path = "./gas"},
    { access = "read", path = "./test/fixtures"},
    { access = "read", path = "./script/bytecode-deploy/build-output"}]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
solc_version = "0.8.24"
evm_version = 'paris'
test = 'test'
via_ir = true
auto_detect_solc = false
auto_detect_remappings = false
deny_warnings = true
no_match_coverage = "test/|script/"
optimizer = true
optimizer_runs = 200

[fuzz]
runs = 1024

[invariant]
runs = 512
fail_on_revert = true
depth = 15

[fmt]
line_length = 120
wrap_comments = true
sort_imports = true
ignore = [
    "src/msca/6900/v0.7/plugins/v1_0_0/addressbook/ColdStorageAddressBookPlugin.sol",
    "src/msca/6900/v0.7/plugins/v1_0_0/acl/SingleOwnerPlugin.sol",
    "src/msca/6900/v0.7/managers/PluginManager.sol",
    "src/msca/6900/v0.7/managers/PluginExecutor.sol",
    "src/msca/6900/v0.7/libs/SelectorRegistryLib.sol",
    "src/msca/6900/v0.7/libs/ExecutionHookLib.sol",
    "src/msca/6900/v0.7/libs/FunctionReferenceDLLLib.sol",
    "src/msca/6900/v0.7/common/Structs.sol",
    "src/msca/6900/v0.7/factories/semi/SingleOwnerMSCAFactory.sol",
    "src/msca/6900/v0.7/factories/UpgradableMSCAFactory.sol",
    "src/msca/6900/v0.7/account/semi/SingleOwnerMSCA.sol",
    "src/msca/6900/v0.7/account/BaseMSCA.sol",
    "src/paymaster/BasePaymaster.sol",
    "src/paymaster/v1/permissioned/SponsorPaymaster.sol",
    "src/utils/PaymasterUtils.sol",
    "src/callback/DefaultCallbackHandler.sol",
    "src/account/v1/factory/ECDSAAccountFactory.sol",
    "test/msca/6900/v0.7/PluginExecutor.t.sol",
    "test/msca/6900/v0.7/TestCircleMSCAFactory.sol",
    "test/msca/6900/v0.7/TestPermitAnyExternalAddressWithPostHookOnlyPlugin.sol",
    "test/msca/6900/v0.7/TestUserOpValidatorWithDependencyHook.sol",
    "test/msca/6900/v0.7/plugins/ColdStorageAddressBookPluginWithFullMSCA.t.sol",
    "test/msca/6900/v0.7/plugins/ColdStorageAddressBookPluginWithSemiMSCA.t.sol",
    "test/msca/6900/v0.7/plugins/ColdStorageAddressBookPluginWrapper.sol",
    "test/msca/6900/v0.7/SingleOwnerPlugin.t.sol",
    "test/msca/6900/v0.7/TestPermitAnyExternalAddressPlugin.sol",
    "test/msca/6900/v0.7/TestPermitAnyExternalAddressWithPreHookOnlyPlugin.sol",
    "test/msca/6900/v0.7/TestTokenPlugin.sol",
    "test/msca/6900/v0.7/PluginManager.t.sol",
    "test/msca/6900/v0.7/TestTokenWithPostHookOnlyPlugin.sol",
    "test/msca/6900/v0.7/TestCircleMSCA.sol",
    "test/msca/6900/v0.7/TestRepeatableFunctionReferenceDLL.sol",
    "test/msca/6900/v0.7/WalletStorageV1Lib.t.sol",
    "test/msca/6900/v0.7/SingleOwnerMSCA.t.sol",
    "test/msca/6900/v0.7/CircularDependencyMock.sol",
    "test/msca/6900/v0.7/TestTokenWithPreHookOnlyPlugin.sol",
    "test/msca/6900/shared/libs/TestAddressDLL.sol",
    "test/msca/6900/shared/libs/TestBytes32DLL.sol",
    "test/libs/RecipientAddressLib.t.sol",
    "test/util/Mock1820Registry.sol",
    "test/SponsorPaymaster.t.sol",
    "test/WalletMigration.t.sol",
    "test/ECDSAAccountAndFactory.t.sol",
    "script/007_DeployColdStorageAddressBookPlugin.s.sol",
    "script/bytecode-deploy/104_DeployColdStorageAddressBookPlugin.s.sol"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
amoy = "${AMOY_RPC_URL}"
arbitrum = "${ARB_RPC_URL}"
arb-sepolia = "${ARB_SEPOLIA_RPC_URL}"
uni-sepolia = "${UNI_SEPOLIA_RPC_URL}"
unichain = "${UNI_RPC_URL}"
base = "${BASE_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
op-sepolia = "${OP_SEPOLIA_RPC_URL}"
op = "${OP_RPC_URL}"
sonic="${SONIC_RPC_URL}"
sonic-blaze="${SONIC_BLAZE_RPC_URL}"
world="${WORLD_RPC_URL}"
world-sepolia="${WORLD_SEPOLIA_RPC_URL}"
celo="${CELO_RPC_URL}"
celo-alfajores="${CELO_ALFAJORES_RPC_URL}"
sei-testnet="${SEI_TESTNET_RPC_URL}"
sei="${SEI_RPC_URL}"
arc-testnet="${ARC_TESTNET_RPC_URL}"
monad-testnet="${MONAD_TESTNET_RPC_URL}"
monad="${MONAD_RPC_URL}"
