[profile.default]
fs_permissions = [{ access = "read-write", path = "./gas"},
    { access = "read", path = "./test/fixtures"},
    { access = "read", path = "./script/bytecode-deploy/build-output"}]
src = 'src'
out = 'out'
libs = ['lib', 'node_modules']
solc_version = "0.8.24"
evm_version = 'paris'
test = 'test'
optimizer = true
optimizer_runs = 200
via_ir = true
auto_detect_solc = false
auto_detect_remappings = false
deny_warnings = true
no_match_coverage = "test/|script/"

[fuzz]
runs = 1024

[invariant]
runs = 512
fail_on_revert = true
depth = 15

[fmt]
line_length = 120
wrap_comments = true
sort_imports = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
amoy = "${AMOY_RPC_URL}"
arbitrum = "${ARB_RPC_URL}"
arb-sepolia = "${ARB_SEPOLIA_RPC_URL}"
uni-sepolia = "${UNI_SEPOLIA_RPC_URL}"
unichain = "${UNI_RPC_URL}"
