name: Continuous Integration
on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: block
          policy: global-allowed-endpoints-policy

      - name: Check out repository code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          submodules: 'recursive'

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run formatter
        run: yarn format:check

      - name: Run linter
        run: yarn lint

      - name: Run unit tests
        run: yarn test

  scan:
    if: github.event_name == 'pull_request'
    uses: circlefin/circle-public-github-workflows/.github/workflows/pr-scan.yaml@v1
