name: Continuous Integration
on:
  pull_request:
  push:
    branches: [master]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup environment
        uses: ./.github/actions/setup

      - name: Run formatter
        run: yarn format:check

      - name: Run linter
        run: yarn lint

      - name: Run unit tests
        run: yarn test

  scan:
    needs: lint_and_test
    if: github.event_name == 'pull_request'
    uses: circlefin/circle-public-github-workflows/.github/workflows/pr-scan.yaml@v1
