name: Coverage
on:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup environment
        uses: ./.github/actions/setup

      # TODO: fail the build if coverage is below the threshold
      # TODO: print the coverage report in the github output
      - name: Run Test Coverage
        run: yarn coverage
