name: Coverage
on:
  pull_request:
  push:
    branches: [master, entry-point-v0.6]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup environment
        uses: ./.github/actions/setup

      # TODO report and check coverage
